# Generated by Django 3.0.3 on 2020-04-13 20:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20200413_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
