# Generated by Django 3.0.3 on 2020-04-13 20:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200413_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
